// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TeamGM.DATA.Context;

namespace Base.DATA.Migrations
{
    [DbContext(typeof(DesafioAtosContext))]
    partial class DesafioAtosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Base.DOMAIN.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Oracle:IdentityIncrement", 1)
                        .HasAnnotation("Oracle:IdentitySeed", 1)
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdEndereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdVenda")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProdutoIdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("VendaIdVenda")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoIdProduto");

                    b.HasIndex("VendaIdVenda");

                    b.ToTable("ItemVenda");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Avaliacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CategoriaProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DescricaoProduto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<byte[]>("FotoProduto")
                        .HasColumnType("RAW(2000)");

                    b.Property<int>("IdFabricante")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantidadeVendas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("ValorProduto")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdProduto");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("IdVenda");

                    b.HasIndex("IdCliente");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.ItemVenda", b =>
                {
                    b.HasOne("Base.DOMAIN.Models.Produto", null)
                        .WithMany("VendaProduto")
                        .HasForeignKey("ProdutoIdProduto");

                    b.HasOne("Base.DOMAIN.Models.Venda", null)
                        .WithMany("ItemVendas")
                        .HasForeignKey("VendaIdVenda");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.Venda", b =>
                {
                    b.HasOne("Base.DOMAIN.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.Produto", b =>
                {
                    b.Navigation("VendaProduto");
                });

            modelBuilder.Entity("Base.DOMAIN.Models.Venda", b =>
                {
                    b.Navigation("ItemVendas");
                });
#pragma warning restore 612, 618
        }
    }
}
